### ISSUE TITLE
BBR TCP algorithm support

### ISSUE THREAD

**Issue by F4bri92** [prorooter007/LightningKernel_Xiaomi_msm8953#1]
Hi, can you enable BBR TCP algorithm?
It should improve performance when network is not so good.

Thank you

**Comment by prorooter007** [comment]
BBR TCP algorithm was enabled already but it was not the default TCP algorithm.
I made it default now. Check the commit below.
Thanks.

https://github.com/prorooter007/LightningKernel_Xiaomi_msm8953/commit/44d631d97a2565eab5b215944a707916e933e590#diff-b462e2218110e024439d0dc75f7c6f39L718
