### ISSUE TITLE
Fails to build within LOS18.1

### ISSUE THREAD

**Issue by LillyWho** [prorooter007/LightningKernel_Xiaomi_msm8953#12]
Unfortunately I'm not an actual kernel developer, so I can't go on the hunt why these errors occur, but it seems whatever commits you pick up fail to compile within the source tree of Lineage. Don't know if it's about the compiler used in this case (I think they now use clang instead of GCC). I hope this log helps.

[log.txt](https://github.com/prorooter007/LightningKernel_Xiaomi_msm8953/files/7644315/log.txt)

**Comment by prorooter007** [comment]
For now, the default branch has some issues.

Currently the working branches are light12testpull and light12test, both of these branches can be compiled using clang.

**Comment by LillyWho** [comment]
Do the branch names refer to Android 12 or is that your internal arbitrary version number? By the way, it does build, but like with any kernel that I try to compile, it fails to boot and drops into fastboot mode.

**Comment by prorooter007** [comment]
Branch name is my internal arbitrary version number. Well it does build and boot, you need to fix your anykernel (I had a similar issue few days back). You can check my anykernel repo for reference.

**Comment by LillyWho** [comment]
I don't use anykernel, I build in-tree as part of an entire ROM build, as I mentioned. Turns out light12test fails to boot dropping to Fastboot, but light12testpull does work. I'm using it right now. The default LOS kernel started not booting with builds a month ago and so I was looking for a more or less maintained replacement, and for now I've found it.

**Comment by prorooter007** [comment]
Good to know that :). By the way, is bluetooth working with light12testpull on your rom??

**Comment by LillyWho** [comment]
I'll test it this evening and if not then I'm open for sharing logcats, dmesg, etc

**Comment by LillyWho** [comment]
Turns out it does, at least Bluetooth audio does. Decent quality, too!

**Comment by prorooter007** [comment]
:)
